In [1]:
import pandas as pd 
import numpy as np
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,confusion_matrix

In [2]:
DATA_DIR=Path().cwd() / "data"
TRAIN_CSV_FILE = DATA_DIR / "train.csv"
TEST_CSV_FILE = DATA_DIR / "test.csv"
RANDOM_STATE = 42
print(DATA_DIR)
print(TRAIN_CSV_FILE)
print(TEST_CSV_FILE)

/home/mdev/Documents/ml/ds-ml-bootcamp/submissions/marshaale/05_assignment/data
/home/mdev/Documents/ml/ds-ml-bootcamp/submissions/marshaale/05_assignment/data/train.csv
/home/mdev/Documents/ml/ds-ml-bootcamp/submissions/marshaale/05_assignment/data/test.csv

## Load Dataset

In [3]:
train_df = pd.read_csv(TRAIN_CSV_FILE)
test_df = pd.read_csv(TEST_CSV_FILE)

In [4]:
train_df.head()

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Status,IncomePerYearEmployed,DebtToIncome
0,-0.070256,0.521042,0.252747,0.134132,0,1,0,-0.281279,0.128642
1,0.001583,-0.128257,0.841758,-0.603593,0,0,1,-0.501191,-0.881289
2,0.192500,-0.488978,-0.854945,0.622754,0,0,1,4.248573,0.444317
3,-0.515483,-0.152305,-0.450549,-0.546108,0,0,1,0.070262,-0.507692
4,-0.734855,-0.096192,-0.556044,-0.541317,1,0,1,-0.017974,-0.243726

In [5]:
test_df.head()

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Status,IncomePerYearEmployed,DebtToIncome
0,0.713141,1.306613,-0.538462,1.211976,0,1,0,1.963379,0.521334
1,-0.167481,0.168337,0.323077,-0.105389,0,1,0,-0.375273,-0.104138
2,0.999726,-0.641283,0.463736,2.180240,0,0,1,0.143460,1.040168
3,1.032700,2.260521,0.147253,-0.114970,1,0,1,0.479935,-0.715778
4,-0.174350,-1.090180,-1.048352,0.431138,0,0,0,18.421969,0.675537

## Prepare Features & Target

In [6]:
X_train = train_df.drop(columns=['Status'])
y_train = train_df['Status']

X_test = test_df.drop(columns=['Status'])
y_test = test_df['Status']

## Train Models (Reproduce Lesson)

In [7]:
rfc = RandomForestClassifier(n_estimators=1000,random_state=RANDOM_STATE)
log_reg = LogisticRegression(max_iter=1000)
svm = SVC(max_iter=1000,random_state=RANDOM_STATE,kernel='sigmoid')
dtree = DecisionTreeClassifier(random_state=RANDOM_STATE)

In [8]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [9]:
log_reg.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [10]:
svm.fit(X_train,y_train)

SVC(kernel='sigmoid', max_iter=1000, random_state=42)

In [11]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [12]:
rfc_predicts = rfc.predict(X_test)
log_reg_predicts = log_reg.predict(X_test)
svm_predicts = svm.predict(X_test)
dtree_predicts = dtree.predict(X_test)

In [31]:
y_test.tolist()

[0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1]

In [32]:
rfc_predicts

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [33]:
log_reg_predicts

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1])

In [34]:
svm_predicts

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])

In [35]:
dtree_predicts

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1])

## Evaluate Performance

In [36]:
# Helpers

def print_metrics(name:str, y_true:pd.Series, y_pred:np.ndarray, pos_label=1):
    acc = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, pos_label=pos_label)
    rec = recall_score(y_true, y_pred, pos_label=pos_label)
    f1 = f1_score(y_true, y_pred, pos_label=pos_label)
    
    print(f"\n{name} Performance:")
    print(f"  Accuracy : {acc:.3f}")
    print(f"  Precision: {precision:.3f}")
    print(f"  Recall   : {rec:.3f}")
    print(f"  F1-Score : {f1:.3f}")

def print_confusion_metrics(y_true:pd.Series, y_pred:np.ndarray):
    cm = confusion_matrix(y_true,y_pred,labels=[1,0])
    cm_df = pd.DataFrame(cm,
        index=["Actual: Approved (1)", "Actual: Rejected (0)"],
        columns=["Pred: Approved (1)", "Pred: Rejected (0)"],
    )
    print(cm)
    return cm_df

def label_str(v:int|float):
    return "Approved (1)" if v == 1 else "Rejected (0)"

In [37]:
print_metrics("Logistic Regression Classifier",y_test,log_reg_predicts)
print_metrics("Random Forest Classifier",y_test,rfc_predicts)
print_metrics("SVM Classifier",y_test,svm_predicts)
print_metrics("Decision Tree Classifier",y_test,dtree_predicts)

Logistic Regression Classifier Performance:
  Accuracy : 0.750
  Precision: 0.750
  Recall   : 0.818
  F1-Score : 0.783

Random Forest Classifier Performance:
  Accuracy : 0.600
  Precision: 0.600
  Recall   : 0.818
  F1-Score : 0.692

SVM Classifier Performance:
  Accuracy : 0.700
  Precision: 0.692
  Recall   : 0.818
  F1-Score : 0.750

Decision Tree Classifier Performance:
  Accuracy : 0.750
  Precision: 0.750
  Recall   : 0.818
  F1-Score : 0.783

In [38]:
print_confusion_metrics(y_test,log_reg_predicts)

[[9 2]
 [3 6]]

                      Pred: Approved (1)  Pred: Rejected (0)
Actual: Approved (1)                   9                   2
Actual: Rejected (0)                   3                   6

In [39]:
print_confusion_metrics(y_test,rfc_predicts)

[[9 2]
 [6 3]]

                      Pred: Approved (1)  Pred: Rejected (0)
Actual: Approved (1)                   9                   2
Actual: Rejected (0)                   6                   3

In [40]:
print_confusion_metrics(y_test,dtree_predicts)

[[9 2]
 [3 6]]

                      Pred: Approved (1)  Pred: Rejected (0)
Actual: Approved (1)                   9                   2
Actual: Rejected (0)                   3                   6

In [41]:
print_confusion_metrics(y_test,svm_predicts)

[[9 2]
 [4 5]]

                      Pred: Approved (1)  Pred: Rejected (0)
Actual: Approved (1)                   9                   2
Actual: Rejected (0)                   4                   5

## Sanity Check

In [42]:
i = 4
x_df = pd.DataFrame([X_test.iloc[i]],columns=X_test.columns.tolist())
y_true = y_test.iloc[i]
x_df

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,IncomePerYearEmployed,DebtToIncome
4,-0.17435,-1.09018,-1.048352,0.431138,0.0,0.0,18.421969,0.675537

In [43]:
print(f"Logistic Regression Prediction: {label_str(log_reg.predict(x_df)[0])}")

Logistic Regression Prediction: Rejected (0)

In [44]:
print(f"Random Forest Prediction: {label_str(rfc.predict(x_df)[0])}")

Random Forest Prediction: Rejected (0)

In [45]:
print(f"Decision Tree Prediction: {label_str(dtree.predict(x_df)[0])}")

Decision Tree Prediction: Approved (1)

In [46]:
print(f"SVM Prediction: {label_str(svm.predict(x_df)[0])}")

SVM Prediction: Rejected (0)

In [47]:
print(f"Actual: {label_str(y_true)}")

Actual: Rejected (0)