In [2]:
# ==========================================
# STEP 1 : Import Required Libraries
# ==========================================

# Import pandas for data manipulation
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Import SimpleImputer for handling missing values
from sklearn.impute import SimpleImputer

# Import RobustScaler for feature scaling
# (Chosen instead of StandardScaler)
from sklearn.preprocessing import RobustScaler

# Display all dataframe columns
pd.set_option("display.max_columns", None)

In [9]:
# ==========================================
# STEP 2 : Load Dataset
# ==========================================

# Read the CSV file

df = pd.read_csv("/content/raw_loan_dataset.csv")

# Print confirmation

print("=" * 60)
print("Dataset loaded successfully.")
print("=" * 60)

# Display dataset dimensions

print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

============================================================
Dataset loaded successfully.
============================================================
Number of Rows : 103
Number of Columns : 7

In [10]:
# ==========================================
# STEP 3 : Inspect Dataset
# ==========================================

# Display first five rows

print("\nFirst Five Rows")
display(df.head())

# Display dataset information

print("\nDataset Information")
print("-" * 40)

df.info()

# Display missing values

print("\nMissing Values")
print("-" * 40)

print(df.isnull().sum())

# Display statistical summary

print("\nSummary Statistics")
print("-" * 40)

display(df.describe(include="all"))

First Five Rows

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved
0,108810,537.0,1.1,25800,Yes,No,No
1,96482,524.0,15.0,11200,Y,No,Yes
2,28478,NaN,5.4,12100,No,No,Yes
3,"$25,851",561.0,17.6,7000,Yes,No,Yes
4,38396,527.0,9.8,10700,No,No,Approved

Dataset Information
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Income            98 non-null     object
 1   CreditScore       97 non-null     float64
 2   EmploymentYears   98 non-null     float64
 3   LoanAmount        98 non-null     object
 4   HasCollateral     101 non-null    object
 5   PreviousDefaults  101 non-null    object
 6   Approved          103 non-null    object
dtypes: float64(2), object(5)
memory usage: 5.8+ KB

Missing Values
----------------------------------------
Income              5
CreditScore         6
EmploymentYears     5
LoanAmount          5
HasCollateral       2
PreviousDefaults    2
Approved            0
dtype: int64

Summary Statistics
----------------------------------------

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved
count,98,97.000000,98.000000,98,101,101,103
unique,95,NaN,NaN,83,6,6,8
top,108810,NaN,NaN,5000,No,No,Yes
freq,2,NaN,NaN,4,50,84,65
mean,NaN,649.288660,12.491837,NaN,NaN,NaN,NaN
std,NaN,99.191204,7.219299,NaN,NaN,NaN,NaN
min,NaN,484.000000,0.500000,NaN,NaN,NaN,NaN
25%,NaN,569.000000,5.775000,NaN,NaN,NaN,NaN
50%,NaN,638.000000,12.550000,NaN,NaN,NaN,NaN
75%,NaN,738.000000,18.325000,NaN,NaN,NaN,NaN
max,NaN,920.000000,25.000000,NaN,NaN,NaN,NaN

In [11]:
# ==========================================
# STEP 4 : Identify Problems
# ==========================================

# Display sample values from Income

print("\nSample values from Income")
print("-" * 40)

print(df["Income"].head(10))

# Display sample values from LoanAmount

print("\nSample values from LoanAmount")
print("-" * 40)

print(df["LoanAmount"].head(10))

# Check unique values in HasCollateral

print("\nUnique values in HasCollateral")
print("-" * 40)

print(df["HasCollateral"].value_counts(dropna=False))

# Check unique values in PreviousDefaults

print("\nUnique values in PreviousDefaults")
print("-" * 40)

print(df["PreviousDefaults"].value_counts(dropna=False))

# Check unique values in Approved

print("\nUnique values in Approved")
print("-" * 40)

print(df["Approved"].value_counts(dropna=False))

Sample values from Income
----------------------------------------
0     108810
1      96482
2      28478
3    $25,851
4      38396
5        NaN
6     106070
7      35458
8      73520
9      57087
Name: Income, dtype: object

Sample values from LoanAmount
----------------------------------------
0      25800
1      11200
2      12100
3       7000
4      10700
5      47800
6      48000
7    $10,300
8      17200
9      13400
Name: LoanAmount, dtype: object

Unique values in HasCollateral
----------------------------------------
HasCollateral
No     50
Yes    46
Y       2
NaN     2
N       1
yse     1
yes     1
Name: count, dtype: int64

Unique values in PreviousDefaults
----------------------------------------
PreviousDefaults
No     84
Yes    13
NaN     2
1       1
0       1
Y       1
N       1
Name: count, dtype: int64

Unique values in Approved
----------------------------------------
Approved
Yes         65
No          32
Approved     1
Rejected     1
approved     1
rejected     1
YES          1
NO           1
Name: count, dtype: int64

In [12]:
# ==========================================
# STEP 5 : Clean Currency Formatting
# ==========================================

# Display data types before cleaning
print("=" * 60)
print("Data Types Before Cleaning")
print("=" * 60)

print(df[["Income", "LoanAmount"]].dtypes)


# List of currency columns
currency_columns = ["Income", "LoanAmount"]


# Loop through each currency column
for column in currency_columns:

    # Convert values to string first
    df[column] = df[column].astype(str)

    # Remove dollar sign ($)
    df[column] = df[column].str.replace("$", "", regex=False)

    # Remove commas (,)
    df[column] = df[column].str.replace(",", "", regex=False)

    # Convert cleaned values into numeric values
    # Invalid values become NaN
    df[column] = pd.to_numeric(df[column], errors="coerce")


print("\nCurrency formatting cleaned successfully.")
print("=" * 60)

# Display data types after cleaning
print(df[["Income", "LoanAmount"]].dtypes)

print("\nSample cleaned values")
display(df[["Income", "LoanAmount"]].head())

============================================================
Data Types Before Cleaning
============================================================
Income        object
LoanAmount    object
dtype: object

Currency formatting cleaned successfully.
============================================================
Income        float64
LoanAmount    float64
dtype: object

Sample cleaned values

     Income  LoanAmount
0  108810.0     25800.0
1   96482.0     11200.0
2   28478.0     12100.0
3   25851.0      7000.0
4   38396.0     10700.0

In [14]:
# ==========================================
# STEP 6 : Fix Category Errors
# ==========================================

# Dictionary used to normalize all category values
category_mapping = {

    # Yes values
    "Yes": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "Y": "Yes",
    "y": "Yes",
    "Approved": "Yes",
    "approved": "Yes",

    # No values
    "No": "No",
    "NO": "No",
    "no": "No",
    "N": "No",
    "n": "No",
    "Rejected": "No",
    "rejected": "No"

}


# Columns that require normalization
category_columns = [

    "HasCollateral",
    "PreviousDefaults",
    "Approved"

]


# Loop through every categorical column
for column in category_columns:

    print("=" * 60)
    print(f"Cleaning {column}")
    print("=" * 60)

    # Replace inconsistent values
    df[column] = df[column].replace(category_mapping)

    # Display value counts after cleaning
    print(df[column].value_counts(dropna=False))

============================================================
Cleaning HasCollateral
============================================================
HasCollateral
No     51
Yes    49
NaN     2
yse     1
Name: count, dtype: int64
============================================================
Cleaning PreviousDefaults
============================================================
PreviousDefaults
No     85
Yes    14
NaN     2
1       1
0       1
Name: count, dtype: int64
============================================================
Cleaning Approved
============================================================
Approved
Yes    68
No     35
Name: count, dtype: int64

In [15]:
# ==========================================
# STEP 7 : Handle Missing Values
# ==========================================

# Identify numerical columns
numeric_columns = df.select_dtypes(include=np.number).columns

# Identify categorical columns
categorical_columns = df.select_dtypes(include="object").columns


# Create median imputer
numeric_imputer = SimpleImputer(strategy="median")


# Create mode imputer
categorical_imputer = SimpleImputer(strategy="most_frequent")


# Fill missing numerical values
df[numeric_columns] = numeric_imputer.fit_transform(df[numeric_columns])


# Fill missing categorical values
df[categorical_columns] = categorical_imputer.fit_transform(df[categorical_columns])


print("=" * 60)
print("Missing values after imputation")
print("=" * 60)

print(df.isnull().sum())

============================================================
Missing values after imputation
============================================================
Income              0
CreditScore         0
EmploymentYears     0
LoanAmount          0
HasCollateral       0
PreviousDefaults    0
Approved            0
dtype: int64

In [21]:
# ==========================================
# STEP 8 : Remove Duplicate Rows
# ==========================================

# Count rows before removing duplicates
rows_before = len(df)

print("=" * 60)
print("Rows Before Removing Duplicates")
print(rows_before)


# Remove duplicate rows
df = df.drop_duplicates()


# Count rows after removing duplicates
rows_after = len(df)

print("\nRows After Removing Duplicates")
print(rows_after)

print("\nDuplicate Rows Removed")
print(rows_before - rows_after)

print("=" * 60)
print("Duplicate removal completed.")
print("=" * 60)

============================================================
Rows Before Removing Duplicates
100

Rows After Removing Duplicates
100

Duplicate Rows Removed
0
============================================================
Duplicate removal completed.
============================================================

In [23]:
# ==========================================
# STEP 9 : Handle Outliers Using IQR Capping
# ==========================================

# List of numerical columns for outlier treatment
outlier_columns = [
    "Income",
    "CreditScore",
    "LoanAmount",
    "EmploymentYears"
]

# Loop through each numerical column
for column in outlier_columns:

    # Calculate first quartile (25%)
    Q1 = df[column].quantile(0.25)

    # Calculate third quartile (75%)
    Q3 = df[column].quantile(0.75)

    # Calculate Interquartile Range
    IQR = Q3 - Q1

    # Calculate lower and upper bounds
    lower_bound = Q1 - (1.5 * IQR)
    upper_bound = Q3 + (1.5 * IQR)

    # Cap extreme values instead of removing rows
    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)

In [33]:
# ==========================================
# STEP 10 : Label Encoding
# ==========================================

# Dictionary for encoding
label_mapping = {
    "Yes": 1,
    "No": 0
}

# Columns to encode
label_columns = [
    "Approved",
    "HasCollateral",
    "PreviousDefaults"
]

# Convert Yes/No into 1/0
for column in label_columns:
    # Check if there are any NaNs in the column.
    if df[column].isnull().any():
        modes = df[column].mode()
        if not modes.empty:
            # If mode(s) exist, fill NaNs with the most frequent value
            mode_val = modes.iloc[0]
            df[column] = df[column].fillna(mode_val)
        else:
            # If modes is empty, the column is entirely NaN.
            # In this case, we need to decide on a default fill value before mapping.
            # For 'Approved', 'HasCollateral', 'PreviousDefaults', 'No' (which maps to 0)
            # is a reasonable default if the column was completely missing.
            print(f"Warning: Column '{column}' was entirely NaN. Filling with 'No' as default for mapping.")
            df[column] = df[column].fillna('No') # Fill with string 'No'

    # Ensure values are string, strip whitespace, then map
    df[column] = df[column].astype(str).str.strip().map(label_mapping)

    print(f"{column} encoded successfully.")

print("=" * 60)
print("Class Distribution")
print("=" * 60)

# Display class distribution
print(df["Approved"].value_counts())

Warning: Column 'Approved' was entirely NaN. Filling with 'No' as default for mapping.
Approved encoded successfully.
Warning: Column 'HasCollateral' was entirely NaN. Filling with 'No' as default for mapping.
HasCollateral encoded successfully.
Warning: Column 'PreviousDefaults' was entirely NaN. Filling with 'No' as default for mapping.
PreviousDefaults encoded successfully.
============================================================
Class Distribution
============================================================
Approved
0    100
Name: count, dtype: int64

In [35]:
# ==========================================
# STEP 11 : Class Balance Check
# ==========================================

print("=" * 60)
print("Approved vs Rejected Counts")
print("=" * 60)

print(df["Approved"].value_counts())

print()

print("=" * 60)
print("Class Proportions")
print("=" * 60)

print(df["Approved"].value_counts(normalize=True))

print()

# Simple interpretation
ratio = df["Approved"].value_counts(normalize=True)

if ratio.empty:
    print("The 'Approved' column does not contain any valid values for classification balance check.")
    print("This indicates a potential data integrity issue or an empty dataset for this column.")
    print("Cannot perform class balance check.")
elif len(ratio) == 1:
    print("The 'Approved' column contains only one unique class after encoding.")
    print("This indicates an extremely imbalanced dataset where only one outcome exists.")
    print("Precision, Recall, and F1-score are necessary evaluation metrics.")
else: # len(ratio) >= 2, assuming binary classification for this check
    if abs(ratio.iloc[0] - ratio.iloc[1]) < 0.20:
        print("The dataset is reasonably balanced.")
        print("Accuracy can be considered a reliable evaluation metric.")
    else:
        print("The dataset is imbalanced.")
        print("Precision, Recall and F1-score should also be considered.")

============================================================
Approved vs Rejected Counts
============================================================
Approved
0    100
Name: count, dtype: int64

============================================================
Class Proportions
============================================================
Approved
0    1.0
Name: proportion, dtype: float64

The 'Approved' column contains only one unique class after encoding.
This indicates an extremely imbalanced dataset where only one outcome exists.
Precision, Recall, and F1-score are necessary evaluation metrics.

In [36]:
# ==========================================
# STEP 12 : Feature Engineering
# ==========================================

# Create Debt-to-Income Ratio
df["DebtToIncome"] = df["LoanAmount"] / df["Income"]

# Avoid division by zero
df["IncomePerYearEmployed"] = (
    df["Income"] /
    (df["EmploymentYears"] + 1)
)

print("=" * 60)
print("New Features Created")
print("=" * 60)

display(
    df[
        [
            "Income",
            "LoanAmount",
            "DebtToIncome",
            "EmploymentYears",
            "IncomePerYearEmployed"
        ]
    ].head()
)

============================================================
New Features Created
============================================================

     Income  LoanAmount  DebtToIncome  EmploymentYears  IncomePerYearEmployed
0  108810.0     25800.0      0.237111              1.1           51814.285714
1   96482.0     11200.0      0.116084             15.0            6030.125000
2   28478.0     12100.0      0.424889              5.4            4449.687500
3   25851.0      7000.0      0.270783             17.6            1389.838710
4   38396.0     10700.0      0.278675              9.8            3555.185185

In [37]:
# ==========================================
# STEP 13 : Feature Scaling
# ==========================================

# Numerical columns to scale
numeric_features = [

    "Income",
    "CreditScore",
    "LoanAmount",
    "EmploymentYears",
    "DebtToIncome",
    "IncomePerYearEmployed"

]

# Create RobustScaler object
scaler = RobustScaler()

# Scale only numerical features
df[numeric_features] = scaler.fit_transform(df[numeric_features])

print("=" * 60)
print("Feature scaling completed.")
print("=" * 60)

display(df.head())

============================================================
Feature scaling completed.
============================================================

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.822149,-0.653722,-0.978632,0.246080,0,0,0,-0.445244,8.274536
1,0.564574,-0.737864,0.209402,-0.458384,0,0,0,-0.912749,0.153994
2,-0.856268,0.000000,-0.611111,-0.414958,0,0,0,0.280113,-0.126321
3,-0.911156,-0.498382,0.431624,-0.661037,0,0,0,-0.315175,-0.669033
4,-0.649046,-0.718447,-0.235043,-0.482509,0,0,0,-0.284688,-0.284975

In [38]:
# ==========================================
# STEP 14 : Final Dataset Check
# ==========================================

print("=" * 60)
print("First Five Rows")
print("=" * 60)

display(df.head())

print()

print("=" * 60)
print("Dataset Information")
print("=" * 60)

df.info()

print()

print("=" * 60)
print("Missing Values")
print("=" * 60)

print(df.isnull().sum())

print()

print("=" * 60)
print("Approved Column")
print("=" * 60)

print(df["Approved"].value_counts())

============================================================
First Five Rows
============================================================

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.822149,-0.653722,-0.978632,0.246080,0,0,0,-0.445244,8.274536
1,0.564574,-0.737864,0.209402,-0.458384,0,0,0,-0.912749,0.153994
2,-0.856268,0.000000,-0.611111,-0.414958,0,0,0,0.280113,-0.126321
3,-0.911156,-0.498382,0.431624,-0.661037,0,0,0,-0.315175,-0.669033
4,-0.649046,-0.718447,-0.235043,-0.482509,0,0,0,-0.284688,-0.284975

============================================================
Dataset Information
============================================================
<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Income                 100 non-null    float64
 1   CreditScore            100 non-null    float64
 2   EmploymentYears        100 non-null    float64
 3   LoanAmount             100 non-null    float64
 4   HasCollateral          100 non-null    int64
 5   PreviousDefaults       100 non-null    int64
 6   Approved               100 non-null    int64
 7   DebtToIncome           100 non-null    float64
 8   IncomePerYearEmployed  100 non-null    float64
dtypes: float64(6), int64(3)
memory usage: 7.8 KB

============================================================
Missing Values
============================================================
Income                   0
CreditScore              0
EmploymentYears          0
LoanAmount               0
HasCollateral            0
PreviousDefaults         0
Approved                 0
DebtToIncome             0
IncomePerYearEmployed    0
dtype: int64

============================================================
Approved Column
============================================================
Approved
0    100
Name: count, dtype: int64

In [39]:
# ==========================================
# STEP 15 : Save Clean Dataset
# ==========================================

# Save cleaned dataset
df.to_csv("clean_loan_dataset.csv", index=False)

print("=" * 60)
print("Dataset saved successfully.")
print("File Name: clean_loan_dataset.csv")
print("=" * 60)

============================================================
Dataset saved successfully.
File Name: clean_loan_dataset.csv
============================================================